version: '3'

services:
  instaiwan-client:
    image: instaiwan/client
    build: .
    command: npm run build
    volumes:
      - ./build:/usr/src/instaiwan/build:instaiwanVolume
    volumes:
      - type: bind
        source: ./build
        target: /usr/src/instaiwan/build:instaiwanVolume
