version: '3'

services:
  instaiwan-client:
    image: instaiwan/client
    build: .
    command: npm run build
    volumes:
      - type: bind
        source: "./build"
        target: "/usr/src/instaiwan/build"
